# ========================================
# FileName: build.yaml
# Date: 07.06.2023
# Author: Marcos Chow Castro
# Email: mctechnology170318@gmail.com
# GitHub: https://github.com/mctechnology17
# Brief: configuration file for ZMK firmware - Modified for Sofle Choc
# Board: nice_nano_v2
# shield: sofle_left, sofle_right with nice_oled
# =========================================

---
include:

  ### SOFLE CHOC START ###
  # nice!nano_v2 + nice_oled for Sofle Choc
  - board: nice_nano_v2
    shield: sofle_left nice_oled
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Sofle_Choc_Oled\" -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_sofle_choc_left_oled
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: sofle_right nice_oled
    cmake-args: -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_sofle_choc_right_oled

  # peripheral_left (if you want to use dongle setup)
  - board: nice_nano_v2
    shield: sofle_left_peripheral nice_oled
    cmake-args: -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_sofle_choc_left_peripheral_oled

  # Xiao_Dongle (optional - for dongle setup)
  - board: seeeduino_xiao_ble
    shield: sofle_dongle_xiao oled_adapter_seeeduino_xiao_ble_128x64 dongle_display
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"SofleChocDongle_X\" -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: xiao_sofle_choc_dongle_xiao_oled
    snippet: studio-rpc-usb-uart

  # ProMicro_Dongle (optional - for dongle setup)
  - board: nice_nano_v2
    shield: sofle_dongle_pro_micro dongle_display
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"SofleChocDongle_P\" -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_SLEEP=n -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_sofle_choc_dongle_oled
    snippet: studio-rpc-usb-uart
  ### SOFLE CHOC END ###

  ### SETTINGS_RESET START ###
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: nice_settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: xiao_settings_reset
  ### SETTINGS_RESET END ###

  ### 아래는 모두 주석처리됨 - 필요시 주석 해제 ###
  
  # ### CORNE START ###
  #   ### nice_view START ###
  #   # nice_nano_v2 + nice_epaper
  # - board: nice_nano_v2
  #   shield: corne_left nice_view_adapter nice_epaper
  #   cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Nice_Corne_View\"
  #   artifact-name: nice_corne_left_view
  #   snippet: studio-rpc-usb-uart
  # - board: nice_nano_v2
  #   shield: corne_right nice_view_adapter nice_epaper
  #   artifact-name: nice_corne_right_view
  
  # ... (나머지 모든 섹션들이 주석처리됨)
